### PR TITLE
feat(marketplace): show content from yaml files, added drawer

### PR DESCRIPTION
**Pull request by christoph-jerolimov**
## Hey, I just made a Pull Request!

* load marketplace data from yaml files
* add subroute to show drawer with initial layout

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
- [ ] Added or Updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by debsmita1** [comment]
The search bar is taking up a lot of space and is cramped against the title

Screenshot 2024-11-22 at 7 11 32 PM

**Comment by christoph-jerolimov** [comment]
> The search bar is taking up a lot of space and is cramped against the title
> 
> Screenshot 2024-11-22 at 7 11 32 PM

That's true, I just wanted setup the structure of the plugin. Also tests are missing yet. It will help us to split the work.

I might work on this later this week. I'm happy if we could merge this anyway but I'm also fine if we wait... :D

**Review by ciiay — APPROVED** [review]
/lgtm

Tested searching and opening side panel, ignored style issues.
Looks good as the initial PR. Thank you 🤝

**Comment by christoph-jerolimov** [comment]
Thanks @ciiay 

@debsmita1. We and I will work on an ui improvement asap :)

**Pull request merged**
