### PR TITLE
fix[bulk-import]: persist changes made to the preview panel for jobs that are waiting for approval

### PR DESCRIPTION
**Pull request by debsmita1**
## Hey, I just made a Pull Request!

**Resolves:**
- https://issues.redhat.com/browse/RHIDP-4955
- https://issues.redhat.com/browse/RHIDP-5145

**GIF/Screenshot:**

https://github.com/user-attachments/assets/5f111c30-825d-40f8-b741-9edaaac7a3b8

Screenshot 2024-12-04 at 6 48 34 PM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/redhat-developer/rhdh-plugins/blob/main/CONTRIBUTING.md#creating-changesets))
- [ ] Added or Updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by christoph-jerolimov** [comment]
Works fine :+1:

just one question for @ShiranHi: Shouldn't we link here the complete text "Waiting for Approval" + external icon and make it a link similar to the columns Repo URL and Organization:

For me, this link is the most important in the row, it's like the CTA like "this is your next step .. get approval"

image

**Comment by ShiranHi** [comment]
The status text should be "Waiting for approval" in gray and then "PR" and the icon [Open in New icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=open&icon.size=24&icon.color=%235f6368) and they should be blue. [Here is the mockup](https://www.figma.com/design/09Iltd57RiuqOtKWkjy8MH/Bulk-import?node-id=3-534&t=wWPHq203pWlPMQlU-1).

**Comment by christoph-jerolimov** [comment]
> The status text should be "Waiting for approval" in gray and then "PR" and the icon [Open in New icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=open&icon.size=24&icon.color=%235f6368) and they should be blue. [Here is the mockup](https://www.figma.com/design/09Iltd57RiuqOtKWkjy8MH/Bulk-import?node-id=3-534&t=wWPHq203pWlPMQlU-1).

I noticed that the Organization column also has just the org name in the designs, not the github.com prefix.

@ShiranHi @debsmita1 should we align this as well? (if this is a value from he backend we can also handle it in another PR. Just want to understand if we want change that?? :))

**Comment by debsmita1** [comment]
> > The status text should be "Waiting for approval" in gray and then "PR" and the icon [Open in New icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=open&icon.size=24&icon.color=%235f6368) and they should be blue. [Here is the mockup](https://www.figma.com/design/09Iltd57RiuqOtKWkjy8MH/Bulk-import?node-id=3-534&t=wWPHq203pWlPMQlU-1).
> 
> I noticed that the Organization column also has just the org name in the designs, not the github.com prefix.
> 
> @ShiranHi @debsmita1 should we align this as well? (if this is a value from he backend we can also handle it in another PR. Just want to understand if we want change that?? :))

Sure, I am on it

**Comment by debsmita1** [comment]
> > > The status text should be "Waiting for approval" in gray and then "PR" and the icon [Open in New icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:open_in_new:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=open&icon.size=24&icon.color=%235f6368) and they should be blue. [Here is the mockup](https://www.figma.com/design/09Iltd57RiuqOtKWkjy8MH/Bulk-import?node-id=3-534&t=wWPHq203pWlPMQlU-1).
> > 
> > 
> > I noticed that the Organization column also has just the org name in the designs, not the github.com prefix.
> > @ShiranHi @debsmita1 should we align this as well? (if this is a value from he backend we can also handle it in another PR. Just want to understand if we want change that?? :))
> 
> Sure, I am on it

Fixed
Screenshot 2024-12-09 at 1 11 44 PM

**Review by ciiay — APPROVED** [review]
/lgtm

Tested working as expected. Thank you 👏

**Pull request merged**
